{% set name = "splines" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/splines-{{ version }}.tar.gz
  sha256: 8a5cf09709254b7872e8bbbfa03aad1dcfa19ec7a49575f3de987c3be17e8a7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - splines
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://splines.readthedocs.io/
  summary: Splines in Euclidean Space and Beyond
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
